source 'https://github.com/CocoaPods/Specs.git'

target 'PXButton' do
  pod "PXButton", :path => "../"
end

target 'Tests' do
  pod "PXButton", :path => "../"
end

target 'PXButton-SwiftExample' do
    pod "PXButton", :path => "../"
end

target 'PXButton-SwiftExampleTests' do
    pod "PXButton", :path => "../"
end
