source 'https://github.com/CocoaPods/Specs.git'

target 'PXButton', :exclusive => true do
  pod "PXButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PXButton", :path => "../"
end
